export const VariableNames = {
  POSITION: 'POSITION',
  VELOCITY: 'VELOCITY',
  ACCELERATION: 'ACCELERATION',
  JERK: 'JERK',
  ORIENTATION: 'ORIENTATION',
  ANGULAR_VELOCITY: 'ANGULAR_VELOCITY',
  ANGULAR_ACCELERATION: 'ANGULAR_ACCELERATION',
  ANGULAR_JERK: 'ANGULAR_JERK'
}
